### Numpy

#### numpy 기본 1. 다차원 배열 만들기

In [1]:
# numpy 임포트
import numpy as np

In [1]:
import numpy as np

In [2]:
# 1차원 배열 생성하기
넘파이_배열1 = np.array([1,2,3,4])
넘파이_배열1

array([1, 2, 3, 4])

In [4]:
넘파이_배열1 = np.array([1,2,3,4])
넘파이_배열1

array([1, 2, 3, 4])

In [3]:
# 2차원 배열 생성하기
넘파이_배열2 = np.array([[1,2,3,4],[11,12,13,14]])
넘파이_배열2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [5]:
넘파이_배열2 = np.array([[1,2,3,4],[11,12,13,14]])
넘파이_배열2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [7]:
print(넘파이_배열2.shape) #행렬이 어떤 모양인지 시각화

(2, 4)


In [4]:
# 3차원 배열 생성하기
넘파이_배열3 = np.array([ [[1,2,3,4],[11,12,13,14]],
                [[21,22,23,24],[31,32,33,34]] ])
넘파이_배열3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [10]:
넘파이_배열3 = np.array([ [[1,2,3,4],[11,12,13,14]],
                   [[21,22,23,24],[31,32,33,34]] ])
넘파이_배열3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [5]:
# 배열의 모양 보기
print(넘파이_배열1.shape)
print(넘파이_배열2.shape)
print(넘파이_배열3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [12]:
print(넘파이_배열1.shape)
print(넘파이_배열2.shape)

(4,)
(2, 4)


In [6]:
z1 = np.zeros([4])    # 0 으로 채운 배열 만들기
o2 = np.ones([3,4])   # 1 로 채운 배열 만들기
r2 = np.random.randn(2,3)   # 랜덤한 숫자 배열 만들기

In [13]:
z1 = np.zeros([4])
o2 = np.ones([3,4])
r2 = np.random.randn(2,3)

In [14]:
z1, o2, r2

(array([0., 0., 0., 0.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[-0.43785494, -2.13051591,  1.37519428],
        [ 0.27949933,  1.08722911,  0.12774568]]))

In [9]:
# 배열의 모양 보기
print(z1.shape)
print(o2.shape)
print(r2.shape)

(4,)
(3, 4)
(2, 3)


In [10]:
# 무척 큰 4차원 배열 생성해보기
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[ 2.985, -1.633, -1.02 , -0.099, -1.98 ],
         [-0.273, -0.531, -0.393,  0.128,  0.018],
         [-0.121,  0.391, -0.491,  0.694,  0.853],
         [ 0.091,  0.453, -0.083, -0.051,  0.24 ]],

        [[-1.318, -0.503,  0.448, -1.078, -0.515],
         [ 0.046,  1.444,  0.188, -0.899, -0.745],
         [-1.375, -0.447,  0.353,  0.007, -0.307],
         [ 0.302, -0.848, -0.609,  0.1  , -0.124]]],


       [[[-0.625, -0.338,  0.968, -0.309, -1.093],
         [-0.035, -1.171, -1.622,  0.714, -0.756],
         [-0.38 ,  2.061, -1.237, -0.558, -1.787],
         [ 2.575,  1.109, -0.498, -1.05 ,  0.168]],

        [[ 0.487, -0.441,  0.247, -1.274, -0.379],
         [ 0.212,  0.156, -0.138,  1.336, -0.016],
         [-1.747,  1.056,  0.209,  0.779,  0.839],
         [ 0.329,  0.599, -0.032, -0.689, -1.579]]]])

In [17]:
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[ 1.21 ,  0.475,  0.791, -0.686,  0.607],
         [ 1.447,  0.542,  0.226,  1.238, -0.801],
         [ 0.476,  0.423, -1.084,  0.291, -0.571],
         [-0.566,  0.012, -0.056, -0.584, -0.827]],

        [[-0.497, -0.12 ,  0.765, -1.792,  1.281],
         [ 1.209, -0.73 ,  0.039,  0.252, -0.486],
         [ 0.484,  1.33 , -1.728,  0.013, -0.188],
         [ 0.965, -0.964, -0.345,  0.578,  0.223]]],


       [[[-0.066,  0.236,  0.484,  1.101,  0.592],
         [ 0.624, -0.588, -0.01 ,  3.275, -0.287],
         [-1.529,  0.763,  0.62 ,  1.862,  0.423],
         [ 0.976, -0.912, -1.234, -0.237, -0.058]],

        [[ 0.523, -0.501, -0.058,  1.003, -1.766],
         [-0.53 ,  0.243, -1.834,  1.865, -1.597],
         [ 0.123,  0.467, -1.109, -1.292, -1.085],
         [-2.068, -0.83 ,  2.342, -0.231, -0.409]]]])

#### numpy 기본 2. Indexing과 Slicing

In [23]:
# r4 배열에서, [두번째][첫번째] 접근해서 가져오기
r4[1][0]

array([[-0.066,  0.236,  0.484,  1.101,  0.592],
       [ 0.624, -0.588, -0.01 ,  3.275, -0.287],
       [-1.529,  0.763,  0.62 ,  1.862,  0.423],
       [ 0.976, -0.912, -1.234, -0.237, -0.058]])

In [18]:
r4[1][0]

array([[-0.066,  0.236,  0.484,  1.101,  0.592],
       [ 0.624, -0.588, -0.01 ,  3.275, -0.287],
       [-1.529,  0.763,  0.62 ,  1.862,  0.423],
       [ 0.976, -0.912, -1.234, -0.237, -0.058]])

In [12]:
r4[1][0][2]

array([-0.38 ,  2.061, -1.237, -0.558, -1.787])

In [24]:
r4[1][0][2]

array([-1.529,  0.763,  0.62 ,  1.862,  0.423])

In [13]:
r4[1][0][2][4]

-1.787

In [25]:
r4[1][0][2][4]

0.423

In [14]:
r4[1,0,2,4]   # 대괄호 대신 쉼표 , 도 차원 접근이 가능

-1.787

In [31]:
r4[1,0,2,4]

r4[1,0]

array([[-0.066,  0.236,  0.484,  1.101,  0.592],
       [ 0.624, -0.588, -0.01 ,  3.275, -0.287],
       [-1.529,  0.763,  0.62 ,  1.862,  0.423],
       [ 0.976, -0.912, -1.234, -0.237, -0.058]])

In [15]:
r4[1][0][2][0:4:2] # 0번 인덱스 부터 4번인덱스 까지 2칸씩 건너 뛰면서

array([-0.38 , -1.237])

In [33]:
r4[1,0,2][0:4:2]

array([-1.529,  0.62 ])

In [16]:
r4[1][0][1:4:2]

array([[-0.035, -1.171, -1.622,  0.714, -0.756],
       [ 2.575,  1.109, -0.498, -1.05 ,  0.168]])

In [37]:
r4[1][0]

array([[-0.066,  0.236,  0.484,  1.101,  0.592],
       [ 0.624, -0.588, -0.01 ,  3.275, -0.287],
       [-1.529,  0.763,  0.62 ,  1.862,  0.423],
       [ 0.976, -0.912, -1.234, -0.237, -0.058]])

In [38]:
r4[1][0][1:4:2]

array([[ 0.624, -0.588, -0.01 ,  3.275, -0.287],
       [ 0.976, -0.912, -1.234, -0.237, -0.058]])

In [17]:
# Indexing과 Slicing 같이 적용하기
r4[1][0][1:4:2][1][3:]

array([-1.05 ,  0.168])

In [40]:
r4[1][0][1:4:2][1][3:] #r4[1][0][1:4:2] 이렇게도 array가 되는 것이니까 이뒤에 [1]처럼 인덱싱 붙이고, 슬라이싱 붙혀서 또 탐색가능

array([-0.237, -0.058])

In [18]:
r4[1,0][1:4:2][1,3:]   # 모두 다 짬뽕!!

array([-1.05 ,  0.168])

In [42]:
r4[1,0][1:4:2][1,3:] #위의 3:변경

array([-0.237, -0.058])

#### numpy 기본 3. 배열 간 연산, Broadcasting, Aggregation

In [19]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [43]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [20]:
arr + arr    # 배열끼리 연산하기 (＋－*/ 모두 가능)

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [44]:
arr+arr

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [21]:
arr + 20     # 덧셈 브로드캐스팅

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [45]:
arr+20

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [22]:
arr * 100    # 곱셈 브로드캐스팅

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [46]:
arr * 100

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [23]:
# 배열 전체의 덧셈, 평균, 곱셈, 최댓값, 최솟값
arr.sum(), arr.mean(), arr.prod(), arr.max(), arr.min()

(56, 7.0, 411840, 13, 1)

In [48]:
arr.sum(),arr.mean(),arr.prod(),arr.max(),arr.min()   #각원소값을 다 더하고, 평균내고, 곱셈,최대,최소 등등

(56, 7.0, 411840, 13, 1)

In [24]:
# 배열에서의 최대인 원소의 번호, 최소인 원소의 번호
arr.argmax(), arr[1].argmax(), arr.argmin()

(7, 3, 0)

In [50]:
arr.argmax(), arr[1].argmax(), arr.argmin()

(7, 3, 0)

In [25]:
# 특정 축(차원)으로 덧셈 수행하기
arr.sum(axis=0), arr.sum(axis=1)

(array([11, 13, 15, 17]), array([10, 46]))

In [51]:
arr.sum(axis = 0), arr.sum(axis = 1) #axis ->축이였던거같음  axis=0이면 열끼리, 1이면 행끼리??

(array([11, 13, 15, 17]), array([10, 46]))

In [26]:
# Indexing + Slicing + Aggregation 응용
arr[1].min(), arr[1][2:].sum()

(10, 25)

In [52]:
arr[1].min(), arr[1][2:].sum()

(10, 25)

#### numpy 기본 4. 고급 Broadcasting

In [27]:
arr1 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
arr1.shape, arr2.shape

((4, 3), (4, 3))

In [54]:
arr1 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
arr1.shape, arr2.shape

((4, 3), (4, 3))

In [28]:
arr1 + arr2          # (4x3)  +  (4x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [55]:
arr1 + arr2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [56]:
arr1 + np.array([0,1,2])     # (4x3) + (1x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [59]:
arr1 +np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [30]:
#  (4x1) + (1x3)
np.array([[0],[10],[20],[30]]) + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [60]:
np.array([[0],[10],[20],[30]]) +np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])